name: r5-secrets-self
on:
  workflow_dispatch:
permissions: read-all
jobs:
  inherit:
    uses: ./.github/workflows/r5-secrets-callee.yml
    secrets: inherit
  none:
    uses: ./.github/workflows/r5-secrets-callee.yml
